name: Build radioracers

on:
  push:

jobs:
  do-everything:
    runs-on: ubuntu-latest

    env:
      CCACHE_CPP2: yes

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./
        with:
          osx-version: "26.1"

      - name: osxcross Config
        run: |
          echo -e "\e[0Ksection_start:`date +%s`:osxcross_Config[collapsed=true]\r\e[0Kosxcross Config"
          export VCPKG_CHAINLOAD_TOOLCHAIN_FILE=${OSXCROSS_TARGET_DIR}/toolchain.cmake
          export PATH="/opt/osxcross.arm64:${PATH}"
          $(osxcross-conf)
          export OSXCROSS_HOST=arm64-apple-${OSXCROSS_TARGET}
          export VCPKG_DEFAULT_TRIPLET=arm64-osx
          export CC=${OSXCROSS_TARGET_DIR}/bin/${OSXCROSS_HOST}-clang
          export CXX=${OSXCROSS_TARGET_DIR}/bin/${OSXCROSS_HOST}-clang++
          export SDKROOT=${OSXCROSS_SDK}
          echo -e "\e[0Ksection_end:`date +%s`:osxcross_Config\r\e[0K"

      - name: apt_development
        run: |
          echo -e "\e[0Ksection_start:`date +%s`:macports_development[collapsed=true]\r\e[0KInstalling development packages"
          osxcross-macports install --static --arm64 curl || osxcross-macports install --verbose --static --arm64 curl || true
          osxcross-macports install --static --arm64 libpng libopus || osxcross-macports install --verbose --static --arm64 libpng libopus
          echo -e "\e[0Ksection_end:`date +%s`:macports_development\r\e[0K"

      - name: cmake
        run: |
          echo -e "\e[0Ksection_start:`date +%s`:cmake[collapsed=false]\r\e[0KBuilding Makefiles"
          cmake --preset ninja-debug \
          -B build.arm64 \
          -G "Unix Makefiles" \
          -DCMAKE_COLOR_DIAGNOSTICS=OFF \
          -DSRB2_CONFIG_ENABLE_WEBM_MOVIES=OFF \
          -DCPM_USE_LOCAL_PACKAGES:BOOL=ON \
          -DOPENMPT_INCLUDE_DIR:PATH="/osxcross/macports/pkgs/opt/local/include" \
          -DSDL2_INCLUDE_DIR:PATH="/osxcross/macports/pkgs/opt/local/lib" \
          -DSRB2_CONFIG_ENABLE_TESTS:BOOL=OFF \
          -DSRB2_CONFIG_SYSTEM_LIBRARIES:BOOL=ON \
          -DSRB2_SDL2_EXE_NAME=ringracers_$CI_PIPELINE_ID \
          -DSRB2_CONFIG_FORCE_NO_MS_BITFIELDS:BOOL=ON \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: make
        run: |
          echo -e "\e[0Ksection_end:`date +%s`:make\r\e[0K"
          echo -e "\e[0Ksection_start:`date +%s`:make[collapsed=false]\r\e[0KCompiling SRB2"
          cmake --build build.arm64 --parallel 1 -- --keep-going
          echo -e "\e[0Ksection_end:`date +%s`:make\r\e[0K"
          echo -e "\e[0Ksection_start:`date +%s`:copy[collapsed=false]\r\e[0KCopying config.h"
          mkdir --parents --verbose build.arm64/dist
          cp --reflink=auto --sparse=always build.arm64/src/config.h build.arm64/dist/arm64.h
          echo -e "\e[0Ksection_end:`date +%s`:copy\r\e[0K"

      - name: Init Python 
        uses: actions/setup-python@v5
        with: 
            python-version: '3.x'

      - name: Build radioracers.pk3
        run: python radio/pk3/pk3make.py radio/pk3/build/radioracers.txt --force -o radio/pk3/out/radioracers.pk3 -b radio/pk3/src/radioracers

      - name: Build radioracers_plus.pk3
        run: python radio/pk3/pk3make.py radio/pk3/build/radioracers_plus.txt --force -o radio/pk3/out/radioracers_plus.pk3 -b radio/pk3/src/radioracers_plus

      - name: Build radioracers_servcfg.pk3
        run: python radio/pk3/pk3make.py radio/pk3/build/radioracers_servcfg.txt --force -o radio/pk3/out/radioracers_servcfg.pk3 -b radio/pk3/src/radioracers_servcfg

      - name: zip compiled build
        run: |
          cd radio/pk3/out
          mv radioracers.pk3 ../../../build.arm64
          mv radioracers_plus.pk3 ../../../build.arm64
          mv radioracers_servcfg.pk3 ../../../build.arm64
          cd ../../../build.arm64
          zip -r radioracers-superstarxalien.zip .

      - name: Upload radioracers as github release
        uses: softprops/action-gh-release@v2
        with:
            tag_name: radioracers-superstarxalien-mac-arm64
            token: ${{ secrets.GITHUB_TOKEN }}
            files: build.cmake/bin/radioracers-superstarxalien-mac-arm64.zip
          