name: Build radioracers

on:
  workflow_dispatch:

jobs:
  do-everything:
    runs-on: ubuntu-latest

    env:
      VCPKG_TARGET_TRIPLET: x64-mingw-static
      CC: x86_64-w64-mingw32-gcc
      CXX: x86_64-w64-mingw32-g++
      LD: x86_64-w64-mingw32-ld

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: vcpkg
        run: |
          echo -e "\e[0Ksection_start:`date +%s`:vcpkg-root[collapsed=true]\r\e[0KSetting vcpkg cache"
          export VCPKG_DEFAULT_BINARY_CACHE="$(pwd)/build/vcpkg-binary-cache"
          mkdir -p "build/vcpkg-binary-cache"
          echo -e "\e[0Ksection_end:`date +%s`:vcpkg-root\r\e[0K"

      - name: apt_toolchain
        run: |
          echo -e "\e[0Ksection_start:`date +%s`:apt_toolchain[collapsed=true]\r\e[0KInstalling toolchain packages"
          sudo apt-get install g++-mingw-w64-x86-64-win32
          echo -e "\e[0Ksection_end:`date +%s`:apt_toolchain\r\e[0K"

      - name: apt_development
        run: |
          echo -e "\e[0Ksection_start:`date +%s`:apt_development[collapsed=true]\r\e[0KInstalling development packages"
          sudo apt-get install ninja-build
          echo -e "\e[0Ksection_end:`date +%s`:apt_development\r\e[0K"

      - name: cmake
        run: |
          sudo apt-get install nasm
          echo -e "\e[0Ksection_start:`date +%s`:cmake[collapsed=false]\r\e[0KBuilding Makefiles"
          cmake \
          --preset ninja-release \
          -B build.cmake \
          -G "Unix Makefiles" \
          -DCMAKE_COLOR_DIAGNOSTICS=OFF \
          -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/toolchains/mingw.cmake \
          -DSRB2_CONFIG_ENABLE_WEBM_MOVIES=OFF \
          -DSRB2_CONFIG_ENABLE_DISCORDRPC=OFF \
          -DCMAKE_TOOLCHAIN_FILE=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake \
          -DVCPKG_TARGET_TRIPLET=${VCPKG_TARGET_TRIPLET} \
          -DSRB2_CONFIG_ALWAYS_MAKE_DEBUGLINK=ON
          echo -e "\e[0Ksection_end:`date +%s`:cmake\r\e[0K"

      - name: make
        run: |
          echo -e "\e[0Ksection_start:`date +%s`:make[collapsed=false]\r\e[0KCompiling SRB2"
          cmake --build build.cmake --parallel 1 -- --keep-going
          echo -e "\e[0Ksection_end:`date +%s`:make\r\e[0K"

      - name: Init Python 
        uses: actions/setup-python@v5
        with: 
            python-version: '3.x'

      - name: Build radioracers.pk3
        run: python radio/pk3/pk3make.py radio/pk3/build/radioracers.txt --force -o radio/pk3/out/radioracers.pk3 -b radio/pk3/src/radioracers

      - name: Build radioracers_plus.pk3
        run: python radio/pk3/pk3make.py radio/pk3/build/radioracers_plus.txt --force -o radio/pk3/out/radioracers_plus.pk3 -b radio/pk3/src/radioracers_plus

      - name: zip compiled build
        run: |
          zip -r radioracers-superstarxalien.zip build.cmake/bin -i radio/pk3/out/radioracers.pk3 radio/pk3/out/radioracers_plus.pk3

      - name: Upload radioracers as github release
        uses: softprops/action-gh-release@v2
        with:
            tag_name: radioracers-superstarxalien-latest
            token: ${{ secrets.GITHUB_TOKEN }}
            files: radioracers-superstarxalien.zip
          